// source: ipc.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.ExifInfo', null, global);
goog.exportSymbol('proto.GenerateThumbnailsRequest', null, global);
goog.exportSymbol('proto.GenerateThumbnailsResponse', null, global);
goog.exportSymbol('proto.MessageType', null, global);
goog.exportSymbol('proto.ReadExifRequest', null, global);
goog.exportSymbol('proto.Thumbnail', null, global);
goog.exportSymbol('proto.ThumbnailType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GenerateThumbnailsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GenerateThumbnailsRequest.repeatedFields_, null);
};
goog.inherits(proto.GenerateThumbnailsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GenerateThumbnailsRequest.displayName = 'proto.GenerateThumbnailsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Thumbnail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Thumbnail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Thumbnail.displayName = 'proto.Thumbnail';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.GenerateThumbnailsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.GenerateThumbnailsResponse.repeatedFields_, null);
};
goog.inherits(proto.GenerateThumbnailsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.GenerateThumbnailsResponse.displayName = 'proto.GenerateThumbnailsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ReadExifRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ReadExifRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ReadExifRequest.displayName = 'proto.ReadExifRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ExifInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ExifInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ExifInfo.displayName = 'proto.ExifInfo';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GenerateThumbnailsRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GenerateThumbnailsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.GenerateThumbnailsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GenerateThumbnailsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GenerateThumbnailsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 1, ""),
    outDir: jspb.Message.getFieldWithDefault(msg, 2, ""),
    typesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GenerateThumbnailsRequest}
 */
proto.GenerateThumbnailsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GenerateThumbnailsRequest;
  return proto.GenerateThumbnailsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GenerateThumbnailsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GenerateThumbnailsRequest}
 */
proto.GenerateThumbnailsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOutDir(value);
      break;
    case 3:
      var value = /** @type {!Array<!proto.ThumbnailType>} */ (reader.readPackedEnum());
      msg.setTypesList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GenerateThumbnailsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GenerateThumbnailsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GenerateThumbnailsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GenerateThumbnailsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOutDir();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTypesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      3,
      f
    );
  }
};


/**
 * optional string path = 1;
 * @return {string}
 */
proto.GenerateThumbnailsRequest.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.GenerateThumbnailsRequest} returns this
 */
proto.GenerateThumbnailsRequest.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string out_dir = 2;
 * @return {string}
 */
proto.GenerateThumbnailsRequest.prototype.getOutDir = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.GenerateThumbnailsRequest} returns this
 */
proto.GenerateThumbnailsRequest.prototype.setOutDir = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated ThumbnailType types = 3;
 * @return {!Array<!proto.ThumbnailType>}
 */
proto.GenerateThumbnailsRequest.prototype.getTypesList = function() {
  return /** @type {!Array<!proto.ThumbnailType>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<!proto.ThumbnailType>} value
 * @return {!proto.GenerateThumbnailsRequest} returns this
 */
proto.GenerateThumbnailsRequest.prototype.setTypesList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {!proto.ThumbnailType} value
 * @param {number=} opt_index
 * @return {!proto.GenerateThumbnailsRequest} returns this
 */
proto.GenerateThumbnailsRequest.prototype.addTypes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.GenerateThumbnailsRequest} returns this
 */
proto.GenerateThumbnailsRequest.prototype.clearTypesList = function() {
  return this.setTypesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Thumbnail.prototype.toObject = function(opt_includeInstance) {
  return proto.Thumbnail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Thumbnail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Thumbnail.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    path: jspb.Message.getFieldWithDefault(msg, 2, ""),
    width: jspb.Message.getFieldWithDefault(msg, 3, 0),
    height: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Thumbnail}
 */
proto.Thumbnail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Thumbnail;
  return proto.Thumbnail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Thumbnail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Thumbnail}
 */
proto.Thumbnail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ThumbnailType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Thumbnail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Thumbnail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Thumbnail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Thumbnail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional ThumbnailType type = 1;
 * @return {!proto.ThumbnailType}
 */
proto.Thumbnail.prototype.getType = function() {
  return /** @type {!proto.ThumbnailType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ThumbnailType} value
 * @return {!proto.Thumbnail} returns this
 */
proto.Thumbnail.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string path = 2;
 * @return {string}
 */
proto.Thumbnail.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Thumbnail} returns this
 */
proto.Thumbnail.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 width = 3;
 * @return {number}
 */
proto.Thumbnail.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.Thumbnail} returns this
 */
proto.Thumbnail.prototype.setWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 height = 4;
 * @return {number}
 */
proto.Thumbnail.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.Thumbnail} returns this
 */
proto.Thumbnail.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.GenerateThumbnailsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.GenerateThumbnailsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.GenerateThumbnailsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.GenerateThumbnailsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GenerateThumbnailsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.Thumbnail.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.GenerateThumbnailsResponse}
 */
proto.GenerateThumbnailsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.GenerateThumbnailsResponse;
  return proto.GenerateThumbnailsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.GenerateThumbnailsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.GenerateThumbnailsResponse}
 */
proto.GenerateThumbnailsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.Thumbnail;
      reader.readMessage(value,proto.Thumbnail.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.GenerateThumbnailsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.GenerateThumbnailsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.GenerateThumbnailsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.GenerateThumbnailsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.Thumbnail.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Thumbnail data = 1;
 * @return {!Array<!proto.Thumbnail>}
 */
proto.GenerateThumbnailsResponse.prototype.getDataList = function() {
  return /** @type{!Array<!proto.Thumbnail>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Thumbnail, 1));
};


/**
 * @param {!Array<!proto.Thumbnail>} value
 * @return {!proto.GenerateThumbnailsResponse} returns this
*/
proto.GenerateThumbnailsResponse.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.Thumbnail=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Thumbnail}
 */
proto.GenerateThumbnailsResponse.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.Thumbnail, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.GenerateThumbnailsResponse} returns this
 */
proto.GenerateThumbnailsResponse.prototype.clearDataList = function() {
  return this.setDataList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ReadExifRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.ReadExifRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ReadExifRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ReadExifRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    path: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ReadExifRequest}
 */
proto.ReadExifRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ReadExifRequest;
  return proto.ReadExifRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ReadExifRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ReadExifRequest}
 */
proto.ReadExifRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ReadExifRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ReadExifRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ReadExifRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ReadExifRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string path = 1;
 * @return {string}
 */
proto.ReadExifRequest.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ReadExifRequest} returns this
 */
proto.ReadExifRequest.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ExifInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.ExifInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ExifInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ExifInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    cameraMake: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cameraModel: jspb.Message.getFieldWithDefault(msg, 2, ""),
    software: jspb.Message.getFieldWithDefault(msg, 3, ""),
    bitsPerSample: jspb.Message.getFieldWithDefault(msg, 4, 0),
    imageWidth: jspb.Message.getFieldWithDefault(msg, 5, 0),
    imageHeight: jspb.Message.getFieldWithDefault(msg, 6, 0),
    imageDescription: jspb.Message.getFieldWithDefault(msg, 7, ""),
    imageOrientation: jspb.Message.getFieldWithDefault(msg, 8, 0),
    imageCopyright: jspb.Message.getFieldWithDefault(msg, 9, ""),
    imageDatetime: jspb.Message.getFieldWithDefault(msg, 10, ""),
    originalDatetime: jspb.Message.getFieldWithDefault(msg, 11, ""),
    digitizeDatetime: jspb.Message.getFieldWithDefault(msg, 12, ""),
    subsecondTime: jspb.Message.getFieldWithDefault(msg, 13, ""),
    exposureTime: jspb.Message.getFieldWithDefault(msg, 14, 0),
    fStop: jspb.Message.getFloatingPointFieldWithDefault(msg, 15, 0.0),
    isoSpeed: jspb.Message.getFieldWithDefault(msg, 16, 0),
    subjectDistance: jspb.Message.getFloatingPointFieldWithDefault(msg, 17, 0.0),
    exposureBias: jspb.Message.getFloatingPointFieldWithDefault(msg, 18, 0.0),
    flashUsed: jspb.Message.getFieldWithDefault(msg, 19, 0),
    meteringMode: jspb.Message.getFieldWithDefault(msg, 20, 0),
    lensFocalLength: jspb.Message.getFloatingPointFieldWithDefault(msg, 21, 0.0),
    focalLength35mm: jspb.Message.getFieldWithDefault(msg, 22, 0),
    gpsLatitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 23, 0.0),
    gpsLongitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 24, 0.0),
    gpsAltitude: jspb.Message.getFloatingPointFieldWithDefault(msg, 25, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ExifInfo}
 */
proto.ExifInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ExifInfo;
  return proto.ExifInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ExifInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ExifInfo}
 */
proto.ExifInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCameraMake(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCameraModel(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSoftware(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBitsPerSample(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setImageWidth(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setImageHeight(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageDescription(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setImageOrientation(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageCopyright(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageDatetime(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalDatetime(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setDigitizeDatetime(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubsecondTime(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setExposureTime(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setFStop(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setIsoSpeed(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSubjectDistance(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setExposureBias(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFlashUsed(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMeteringMode(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLensFocalLength(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFocalLength35mm(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGpsLatitude(value);
      break;
    case 24:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGpsLongitude(value);
      break;
    case 25:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGpsAltitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ExifInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ExifInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ExifInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ExifInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCameraMake();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCameraModel();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSoftware();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getBitsPerSample();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getImageWidth();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getImageHeight();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getImageDescription();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getImageOrientation();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getImageCopyright();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getImageDatetime();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getOriginalDatetime();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getDigitizeDatetime();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getSubsecondTime();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getExposureTime();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getFStop();
  if (f !== 0.0) {
    writer.writeDouble(
      15,
      f
    );
  }
  f = message.getIsoSpeed();
  if (f !== 0) {
    writer.writeUint32(
      16,
      f
    );
  }
  f = message.getSubjectDistance();
  if (f !== 0.0) {
    writer.writeDouble(
      17,
      f
    );
  }
  f = message.getExposureBias();
  if (f !== 0.0) {
    writer.writeDouble(
      18,
      f
    );
  }
  f = message.getFlashUsed();
  if (f !== 0) {
    writer.writeInt32(
      19,
      f
    );
  }
  f = message.getMeteringMode();
  if (f !== 0) {
    writer.writeUint32(
      20,
      f
    );
  }
  f = message.getLensFocalLength();
  if (f !== 0.0) {
    writer.writeDouble(
      21,
      f
    );
  }
  f = message.getFocalLength35mm();
  if (f !== 0) {
    writer.writeUint32(
      22,
      f
    );
  }
  f = message.getGpsLatitude();
  if (f !== 0.0) {
    writer.writeDouble(
      23,
      f
    );
  }
  f = message.getGpsLongitude();
  if (f !== 0.0) {
    writer.writeDouble(
      24,
      f
    );
  }
  f = message.getGpsAltitude();
  if (f !== 0.0) {
    writer.writeDouble(
      25,
      f
    );
  }
};


/**
 * optional string camera_make = 1;
 * @return {string}
 */
proto.ExifInfo.prototype.getCameraMake = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setCameraMake = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string camera_model = 2;
 * @return {string}
 */
proto.ExifInfo.prototype.getCameraModel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setCameraModel = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string software = 3;
 * @return {string}
 */
proto.ExifInfo.prototype.getSoftware = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setSoftware = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 bits_per_sample = 4;
 * @return {number}
 */
proto.ExifInfo.prototype.getBitsPerSample = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setBitsPerSample = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 image_width = 5;
 * @return {number}
 */
proto.ExifInfo.prototype.getImageWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setImageWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 image_height = 6;
 * @return {number}
 */
proto.ExifInfo.prototype.getImageHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setImageHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string image_description = 7;
 * @return {string}
 */
proto.ExifInfo.prototype.getImageDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setImageDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional uint32 image_orientation = 8;
 * @return {number}
 */
proto.ExifInfo.prototype.getImageOrientation = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setImageOrientation = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional string image_copyright = 9;
 * @return {string}
 */
proto.ExifInfo.prototype.getImageCopyright = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setImageCopyright = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string image_datetime = 10;
 * @return {string}
 */
proto.ExifInfo.prototype.getImageDatetime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setImageDatetime = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string original_datetime = 11;
 * @return {string}
 */
proto.ExifInfo.prototype.getOriginalDatetime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setOriginalDatetime = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string digitize_datetime = 12;
 * @return {string}
 */
proto.ExifInfo.prototype.getDigitizeDatetime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setDigitizeDatetime = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string subsecond_time = 13;
 * @return {string}
 */
proto.ExifInfo.prototype.getSubsecondTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setSubsecondTime = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional int32 exposure_time = 14;
 * @return {number}
 */
proto.ExifInfo.prototype.getExposureTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setExposureTime = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional double f_stop = 15;
 * @return {number}
 */
proto.ExifInfo.prototype.getFStop = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 15, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setFStop = function(value) {
  return jspb.Message.setProto3FloatField(this, 15, value);
};


/**
 * optional uint32 iso_speed = 16;
 * @return {number}
 */
proto.ExifInfo.prototype.getIsoSpeed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setIsoSpeed = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional double subject_distance = 17;
 * @return {number}
 */
proto.ExifInfo.prototype.getSubjectDistance = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 17, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setSubjectDistance = function(value) {
  return jspb.Message.setProto3FloatField(this, 17, value);
};


/**
 * optional double exposure_bias = 18;
 * @return {number}
 */
proto.ExifInfo.prototype.getExposureBias = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 18, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setExposureBias = function(value) {
  return jspb.Message.setProto3FloatField(this, 18, value);
};


/**
 * optional int32 flash_used = 19;
 * @return {number}
 */
proto.ExifInfo.prototype.getFlashUsed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setFlashUsed = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional uint32 metering_mode = 20;
 * @return {number}
 */
proto.ExifInfo.prototype.getMeteringMode = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setMeteringMode = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional double lens_focal_length = 21;
 * @return {number}
 */
proto.ExifInfo.prototype.getLensFocalLength = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 21, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setLensFocalLength = function(value) {
  return jspb.Message.setProto3FloatField(this, 21, value);
};


/**
 * optional uint32 focal_length_35mm = 22;
 * @return {number}
 */
proto.ExifInfo.prototype.getFocalLength35mm = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setFocalLength35mm = function(value) {
  return jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * optional double gps_latitude = 23;
 * @return {number}
 */
proto.ExifInfo.prototype.getGpsLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 23, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setGpsLatitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 23, value);
};


/**
 * optional double gps_longitude = 24;
 * @return {number}
 */
proto.ExifInfo.prototype.getGpsLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 24, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setGpsLongitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 24, value);
};


/**
 * optional double gps_altitude = 25;
 * @return {number}
 */
proto.ExifInfo.prototype.getGpsAltitude = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 25, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.ExifInfo} returns this
 */
proto.ExifInfo.prototype.setGpsAltitude = function(value) {
  return jspb.Message.setProto3FloatField(this, 25, value);
};


/**
 * @enum {number}
 */
proto.MessageType = {
  PING: 0,
  GENERATETHUMBNAILS: 1,
  READEXIF: 2
};

/**
 * @enum {number}
 */
proto.ThumbnailType = {
  SMALL: 0,
  MEDIUM: 1,
  LARGE: 2
};

goog.object.extend(exports, proto);
